### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by tbergeron** [pickerin/joplin-update-frontmatter#1]
Just wanted to drop a quick thanks for creating that script. It's a clever way to use the Clipper API and it did exactly what I needed.
I missed all my tags and it was really important for me to retain them while exporting to Obsidian so thanks to you all my notes are as I intended them!

You can close that issue right away, just wanted to say thanks for sharing the script. It worked flawlessly on my Windows 10 machine.

Have a great day!

**Comment by pickerin** [comment]
Awesome, glad it worked for you!
